version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soa
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d soa"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  first-service:
    build: ./first-service
    container_name: first-service
    hostname: localhost
    ports:
      - "8080:8080"
      - "4848:4848" # Admin console
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: soa
      DB_USER: user
      DB_PASSWORD: password
      JAVA_OPTS: "-Dcom.sun.aas.hostName=localhost"
    volumes:
      - gradle-cache:/home/gradle/.gradle
    restart: always

  second-service:
    build: ./second-service
    container_name: second-service
    ports:
      - "8081:8080"
      - "8443:8443"
    depends_on:
      - first-service
    volumes:
      - gradle-cache:/home/gradle/.gradle
    environment:
      - JAVA_OPTS=-Djava.util.logging.ConsoleHandler.level=Debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

volumes:
  postgres-data:
  gradle-cache:
