version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soa
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d soa"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  first-service:
    build:
      context: .
      dockerfile: first-service/Dockerfile
    container_name: first-service
    # наружу больше НЕ публикуем: ходим через фронтовый Nginx
    expose:
      - "8443"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: soa
      DB_USER: user
      DB_PASSWORD: password
      JAVA_OPTS: >
        -Djavax.net.ssl.trustStore=/opt/certs/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
      SRV_STORE_PASS: 123456
    volumes:
      - gradle-cache:/home/gradle/.gradle
    restart: always

  second-service:
    build:
      context: .
      dockerfile: second-service/Dockerfile
    container_name: second-service
    # тоже не торчим наружу
    expose:
      - "8443"
    depends_on:
      - first-service
    environment:
      JAVA_OPTS: >
        -Djava.util.logging.ConsoleHandler.level=Debug
        -Djavax.net.ssl.trustStore=/opt/jboss/wildfly/standalone/configuration/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8445:443" # фронт доступен снаружи по https://144.31.193.121:8445
    depends_on:
      - first-service
      - second-service
    restart: always

volumes:
  postgres-data:
  gradle-cache:
