version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soa
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d soa"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  first-service:
    build:
      context: . # теперь корень проекта
      dockerfile: first-service/Dockerfile
    container_name: first-service
    ports:
      - "8443:8443" # HTTPS приложения
      - "4848:4848" # Payara admin (по http, только локально)
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: soa
      DB_USER: user
      DB_PASSWORD: password
      JAVA_OPTS: >
        -Djavax.net.ssl.trustStore=/opt/certs/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
      # Выполняем post-boot команды Payara (см. скрипт)
      SRV_STORE_PASS: 123456
    volumes:
      - gradle-cache:/home/gradle/.gradle
    restart: always

  second-service:
    build:
      context: . # тоже из корня
      dockerfile: second-service/Dockerfile
    container_name: second-service
    ports:
      - "8444:8443" # HTTPS второго сервиса наружу на другой порт
    depends_on:
      - first-service
    environment:
      JAVA_OPTS: >
        -Djava.util.logging.ConsoleHandler.level=Debug
        -Djavax.net.ssl.trustStore=/opt/jboss/wildfly/standalone/configuration/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8445:443"
    depends_on:
      - first-service
      - second-service
    restart: always

volumes:
  postgres-data:
  gradle-cache:
